KINESIS_PLATFORM_VERSION = unova

KINESIS_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)

KINESIS_BUILDTYPE ?= UNOFFICIAL

KINESIS_VERSION_SUFFIX := $(KINESIS_BUILD_DATE)-$(KINESIS_BUILDTYPE)$(KINESIS_EXTRAVERSION)

# Internal version
KINESIS_VERSION := $(KINESIS_PLATFORM_VERSION)-$(KINESIS_VERSION_SUFFIX)-$(KINESIS_BUILD)

# Display version
KINESI_DISPLAY_VERSION := $(KINESIS_PLATFORM_VERSION)-$(KINESIS_VERSION_SUFFIX)
